// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgOF8bLEiU8HL7NllS2fEnVSyJZoEZkqo',
    appId: '1:892714718220:web:a83efee5c552554d81ca29',
    messagingSenderId: '892714718220',
    projectId: 'docudate-b6d87',
    authDomain: 'docudate-b6d87.firebaseapp.com',
    storageBucket: 'docudate-b6d87.firebasestorage.app',
    measurementId: 'G-Q52YHB4HN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHGdVse9QGbDG2-Z5PGVYqQRNPeyhuD6s',
    appId: '1:892714718220:android:b021ef61928e9d8f81ca29',
    messagingSenderId: '892714718220',
    projectId: 'docudate-b6d87',
    storageBucket: 'docudate-b6d87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd-66cgQTKs6aLoehlL1r7vDBH2VP1b-Y',
    appId: '1:892714718220:ios:cd46d354d80f0f0581ca29',
    messagingSenderId: '892714718220',
    projectId: 'docudate-b6d87',
    storageBucket: 'docudate-b6d87.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd-66cgQTKs6aLoehlL1r7vDBH2VP1b-Y',
    appId: '1:892714718220:ios:cd46d354d80f0f0581ca29',
    messagingSenderId: '892714718220',
    projectId: 'docudate-b6d87',
    storageBucket: 'docudate-b6d87.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgOF8bLEiU8HL7NllS2fEnVSyJZoEZkqo',
    appId: '1:892714718220:web:a0714406732fefcd81ca29',
    messagingSenderId: '892714718220',
    projectId: 'docudate-b6d87',
    authDomain: 'docudate-b6d87.firebaseapp.com',
    storageBucket: 'docudate-b6d87.firebasestorage.app',
    measurementId: 'G-Y7YZR1WRWR',
  );
}
